config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms do
    resources :messages
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  include CableReady::Broadcaster
  belongs_to :room
  belongs_to :user
  after_create_commit do
    broadcast_append_to "messages_#{self.room_id}", target: "messages_#{self.room_id}"
    broadcast_update_to "messages", target: "count_message_#{self.room_id}", html: self.room.messages.count
  end
  after_update_commit { broadcast_replace_to "message_#{self.id}", target: "message_#{self.id}"  }
  after_destroy_commit do
    broadcast_remove_to "messages", target: "message_#{self.id}"
    broadcast_update_to "messages", target: "count_message_#{self.room_id}", html: self.room.messages.count
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  after_create_commit { broadcast_append_to "chat_rooms", target: "chat_rooms" }
  after_update_commit { broadcast_replace_to "chat_rooms", target: "room_#{self.id}"  }
  after_destroy_commit { broadcast_remove_to "chat_rooms", target: "room_#{self.id}"  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[ new create ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = @room.messages.build(user_id: current_user.id)
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = @room.messages.build(message_params)
    @message.user_id = current_user.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to room_url(@room), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:room_id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExampleHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body class="align-middle">
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Hotwire Chat</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <%=link_to "New Room", new_room_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%=link_to "Your account", edit_user_registration_path, class: 'nav-link' %>
            </li>
          </ul>
          <span class="navbar-text">
            <%=link_to "Logout", destroy_user_session_path, method: :delete %>
          </span>
        </div>
      </div>
    </nav>
    <div class="container">
      <main>
        <%= yield %>
        <% if user_signed_in? %>
        <hr />
        <div class="btn-group" role="group" aria-label="Actions">
          <%= link_to "New room", new_room_path, class: 'btn btn-primary' %>
          <%= link_to "Back to rooms", rooms_path, class: 'btn btn-secondary' %>
        </div>
        <% end %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExampleHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag "devise", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
    <body class="text-center">
      <main class="form-signin">
        <%= yield %>
      </main>
  </body>
</html>

app/views/messages/_form.html.erb
<%= bootstrap_form_for(message, url: [message.room, message],
data:  {controller: "hello", action: "turbo:submit-end->hello#reset"}) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_area :content %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="card mb-3" id="<%= dom_id message %>">
  <div class="card-body">
    <p class="card-text"><%= message.content %></p>
    <p class="card-footer"><%= l message.created_at, format: :short %> | <strong><%=message.user.email%></strong> </p>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>
<%= turbo_frame_tag "new_message" do %>
  <%= render "form", message: @message %>
<% end %>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

app/views/rooms/_form.html.erb
<%= bootstrap_form_for(room) do |form| %>
<div class="card">
  <div class="card-body">
    <p class="card-text">

        <% if room.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

            <ul>
              <% room.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= form.text_field :name %>

      </p>
    </div>
    <div class="card-footer">
      <%= turbo_frame_tag "chat_rooms" do %>
        <div class="btn-group" role="group" aria-label="Actions">
          <%= form.submit 'Save', class: 'btn btn-success' %>
          <% unless room.new_record? %>
            <%= link_to "Show this room", room, class: 'btn btn-primary', 'data-turbo-frame': '_top' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>" class="card mb-3">
  <div class="card-body">
    <p class="card-text"><%= room.name %></p>
  </div>
  <div class="card-footer">Mensagens:
    <%= turbo_stream_from "messages" %>
    <span id="count_message_<%=room.id%>"><%=room.messages.count %></span>
  </div>
  <div class="card-footer">
    <%= link_to "Edit this room", edit_room_path(room), class: 'btn btn-success' %>
  </div>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= turbo_frame_tag "chat_rooms" do %>
  <%= render "form", room: @room %>
<% end %>

<hr />
<hr />

<h5>Messages</h5>
<%= turbo_stream_from "messages_#{@room.id}" %>
<%= turbo_frame_tag "messages_#{@room.id}" do %>
  <%= render partial: "messages/message", collection: @room.messages, locals: {user: current_user} %>
<% end %>
<hr />
<hr />
<%= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: "messages_#{@room.id}", locals: {user: current_user} %>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<%= turbo_stream_from "chat_rooms" %>
<%= turbo_frame_tag "chat_rooms" do %>
  <%=render @rooms %>
<% end %>

app/views/rooms/new.html.erb
<%= turbo_frame_tag 'new_chat_room', target: "_top" do %>
  <%= render "form", room: @room %>
<% end %>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>
<%= turbo_stream_from "chat_rooms" %>
<%= turbo_frame_tag "chat_rooms" do %>
  <%= render @room %>
<% end %>
<hr />
<hr />

<h5>Messages</h5>
<%= turbo_stream_from "messages_#{@room.id}" %>
<%= turbo_frame_tag "messages_#{@room.id}" do %>
  <%= render partial: "messages/message", collection: @room.messages, locals: {user: current_user} %>
<% end %>
<hr />
<hr />
<%= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: "messages_#{@room.id}" %>